### ISSUE TITLE
[bug] makes the first column disappear but highlights won't show up

### ISSUE THREAD

**Issue by ibhagwan** [brenoprata10/nvim-highlight-colors#1]
Hi,

Great initiative, love the idea of hijacking the sign column.

Doesn't seem to work though with `bluz71/vim-nightfly-guicolors`, it makes the first column disappear but the highlights don't show up, tried with both `0.7.2` and the nightly:
> the first character is `l` in `let`
![image](https://user-images.githubusercontent.com/59988195/180328497-dfcb178c-8cec-4073-ae69-4402a0c06555.png)

If I change it to another colorscheme (my own version of embark) it does seem to work after a toggle (have to turn off and then on) but again hides the first column text (is that supposed to work this way?):
![image](https://user-images.githubusercontent.com/59988195/180328651-005362fb-d94e-4a55-91dd-1df0d4a64bfe.png)

**Comment by brenoprata10** [comment]
Could you post the whole line here for me to do some magical debugging? 🪄 😁

**Comment by brenoprata10** [comment]
Which colorscheme did you use for the first screenshot?

**Comment by ibhagwan** [comment]
> Could you post the whole line here for me to do some magical debugging? 🪄 😁

My entire configuration can be found [here](https://github.com/ibhagwan/nvim-lua), the file in the image was [embark.vim](https://github.com/ibhagwan/nvim-lua/blob/main/colors/embark.vim).

> Which colorscheme did you use for the first screenshot?

The first screenshot is using [vim-nightfly-colors](https://github.com/bluz71/vim-nightfly-guicolors), the second screenshot is from my own variation of embark, [lua-embark](https://github.com/ibhagwan/nvim-lua/blob/main/colors/lua-embark.lua).

**Comment by brenoprata10** [comment]
Thanks, i'll take a look once i am available.
Would you mind trying out branch `feature-multiple-colors`? This branch should display the first char column and could potentially fix this issue :bow:

**Comment by brenoprata10** [comment]
The first column char should be fixed on main branch, please update the plugin

**Comment by ibhagwan** [comment]
> The first column char should be fixed on main branch, please update the plugin

Works great, tysm!
