### ISSUE TITLE
not working for named colors: `orange`, `deepskyblue`

### ISSUE THREAD

**Issue by daUnknownCoder** [brenoprata10/nvim-highlight-colors#102]
im doing this:
```lua
  -- Asynchronous highlight of HEX colors
  {
    "brenoprata10/nvim-highlight-colors",
    event = { "VeryLazy" },
    config = function()
      local nvim_highlight_colors_status_ok, nvim_highlight_colors = pcall(require, "nvim-highlight-colors")
      if not nvim_highlight_colors_status_ok then
        print("nvim_highlight_colors not found!")
      end
      nvim_highlight_colors.setup({
        render = "background",
        enable_hex = true,
        enable_short_hex = true,
        enable_rgb = true,
        enable_hsl = true,
        enable_var_usage = true,
        enable_named_colors = true,
        enable_tailwind = true,
        exclude_filetypes = { "text" },
      })
    end,
    lazy = true,
  },
```

but it doesnt work for named colors, i tested for `hsl`, `rgb`, `#`, `tailwind` and it works for them
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/84800625/cab91eee-75af-4c01-8cc7-f9723b8a1025)

so how to solve this?

**Comment by brenoprata10** [comment]
There is a safe guard in the plugin that exists to prevent false positives, named colors will get highlighted if they are being used as a value e.g. `background: blue` or `background = blue`.
This was created to avoid highlighting situations like `we love blueberries` getting the `blue` part highlighted

**Comment by daUnknownCoder** [comment]
> There is a safe guard in the plugin that exists to prevent false positives, named colors will get highlighted if they are being used as a value e.g. `background: blue` or `background = blue`. This was created to avoid highlighting situations like `we love blueberries` getting the `blue` part highlighted

but if you see the image, in the table, i have this virtext thing which has colors `Orange` and `deepskyblue` which are not getting highlighted and aint a false positive too? thoughts?
