### ISSUE TITLE
Add colors inside lsp action

### ISSUE THREAD

**Issue by t1gu1** [brenoprata10/nvim-highlight-colors#104]
Is there a way to add the **cutom colors** there too?
Could be nice to have a true/false option for that.

![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/12479055/328facc1-5239-4865-b72e-aa0c730d529c)

By the way, thx for that nice and easy plugin!

**Comment by GR3YH4TT3R93** [comment]
If you use tailwind (doesn't look like it from your screenshot but I figured I'd throw it out there) check out [cmp-tailwind-colors](https://github.com/js-everts/cmp-tailwind-colors). Maybe @brenoprata10 can look it over and see if there's anything that could be adapted?

**Comment by brenoprata10** [comment]
That's actually a really good suggestion :)

**Comment by brenoprata10** [comment]
Just pushed the integration. Check the README and let me know what do you think of it 😄

**Comment by brenoprata10** [comment]
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/26099427/632e4a6c-53c1-4b02-92bd-01ed1ad71597)

**Comment by t1gu1** [comment]
@GR3YH4TT3R93
Oh, i'm not using tailwind.
I use a 100% custom solution(I don't want to be slow by a framework updates) heavily inspired by tailwind in react-native, but thx for the suggestion! (It may helps other)

---

@brenoprata10 
Yay! I updated my packages and I saw the difference. Thx!
It is really usefull!
