### ISSUE TITLE
Clarify integration with `nvim-cmp` format()

### ISSUE THREAD

**Issue by savchenko** [brenoprata10/nvim-highlight-colors#109]
An example in the readme assumes that format isn't being already used. However, it is often declared as a function, e.g. 

```lua
format = function(_, item)
  -- many customisations...
  return item
end
```

How do I _correctly_ hook `nvim-highlight-colours` there?

**Comment by nickp-real** [comment]
https://github.com/brenoprata10/nvim-highlight-colors/blob/f4b659383a940b4f3121bca550c3461dec6d1a16/lua/nvim-highlight-colors/init.lua#L175

In the code I assume you can use it by

```lua
format = function(entry, item)
  ...custom config
  return require("nvim-highlight-colors").format
end
```

**Comment by brenoprata10** [comment]
> An example in the readme assumes that format isn't being already used. However, it is often declared as a function, e.g.
> 
> ```lua
> format = function(_, item)
>   -- many customisations...
>   return item
> end
> ```
> 
> How do I _correctly_ hook `nvim-highlight-colours` there?

Hey o/

I've updated the readme. Please check it out :)
