### ISSUE TITLE
cmp integration background highlight issues

### ISSUE THREAD

**Issue by nickp-real** [brenoprata10/nvim-highlight-colors#110]
My config
```lua
formatting = {
  fields = { "kind", "abbr", "menu" },
  format = function(entry, item)
    item = require("nvim-highlight-colors").format(entry, item)
    -- the item.abbr returns the user's virtual object eg. the square when it's Color entry
    if item.abbr == "" then
      -- I have kind_icons table looks like kind_icons = { Text = "Tt (this is icon)", ...more icons }
      item.kind = string.format("%s", kind_icons[item.menu])
    else
      item.kind = item.abbr
    end
    item.abbr = item.word
    item.kind_hl_group = item.abbr_hl_group or nil
    item.abbr_hl_group = nil
    return item
end,
}
```

The problem I found is the highlight group (nvim-highlight-000000, ...) doesn't link the bg highlight to the current theme highlight (maybe using the Normal group)
and another one is when I have a custom tailwind variable, it doesn't apply eg text-primary

This is the result, some work when you first see it (type the text and it shows) then when scrolling down and scrolling back, the background color turns to the highlight color group instead
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/69962410/223f1ea0-38fa-46be-8a13-d69d85907ed5)

before select item
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/69962410/82f73f52-b2c6-4fa3-ad6c-51a47bd144db)

after select item
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/69962410/89417d08-67b9-476d-8d8e-8a82ccc06f53)

my config with a custom icon
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/69962410/3aa5da1b-dbd2-4c43-8167-c65bfe0127be)

_Originally posted by @nickp-real in https://github.com/brenoprata10/nvim-highlight-colors/issues/109#issuecomment-2198428197_

**Comment by brenoprata10** [comment]
Hey o/
I am not really able to reproduce your issue, the scrolling and selection of my vanilla config is working fine. 
I recommend calling my `format` function at the very bottom of the nvim-cmp format. Check the README for more info

**Comment by mehalter** [comment]
Hm I am also getting this 🤔 even with the format being set to only `nvim-highlight-colors`:

```lua
formatting = {
  fields = { "kind", "abbr", "menu" },
  format = require("nvim-highlight-colors").format
}
```

**Comment by mehalter** [comment]
It seems to simply be highlight collisions. Opening a PR now to fix this

**Comment by brenoprata10** [comment]
Thanks man! 💯
