### ISSUE TITLE
Unclear how to integrate with lspkind

### ISSUE THREAD

**Issue by pgosar** [brenoprata10/nvim-highlight-colors#111]
Hi, from the README, it is still unclear to me about how to integrate this with lspkind. I cannot set item equal to this function as I get this issue `attempt to index local 'item' (a function value)`.  I've tried a couple variations of manually setting item's subfields, but short of defining my own separate symbol table and removing lspkind entirely, I've been unable to integrate this completely.

```lua
formatting = {
fields = { "abbr", "kind", "menu" },
format = function(entry, item)
	item = require("lspkind").cmp_format({
		maxwidth = 50,
		ellipsis_char = "...",
		mode = "symbol_text",
		symbol_map = { Copilot = "" },
		show_labelDetails = true,
	})
	return require("nvim-highlight-colors").format(entry, item)
end,
},
```

**Comment by brenoprata10** [comment]
What about 
```
format = function(entry, item)
	item = require("lspkind").cmp_format({
		maxwidth = 50,
		ellipsis_char = "...",
		mode = "symbol_text",
		symbol_map = { Copilot = "" },
		show_labelDetails = true,
	})(entry,item)
	return require("nvim-highlight-colors").format(entry, item)
end,
},
```

**Comment by brenoprata10** [comment]
https://github.com/onsails/lspkind.nvim/blob/1735dd5a5054c1fb7feaf8e8658dbab925f4f0cf/lua/lspkind/init.lua#L180

**Comment by pgosar** [comment]
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/55164602/08e27e2a-2fbb-4297-8dc2-ccc5f0e67693)
with that, I get this. Here's what I had before - the expected behavior is for everything to stay the same but with those colored boxes added on the left

![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/55164602/e7a3876c-d667-41e2-bd55-e9c66f11e3cf)

**Comment by brenoprata10** [comment]
Hum, I have no idea how to help you with this one to be honest hahahaha
I don't use lspkind, so I have no idea how to solve this 😢 

I will be closing this one for now

**Comment by mehalter** [comment]
@pgosar I opened a PR that updates the README on how to integrate with `lspkind`

**Comment by pgosar** [comment]
I just saw it, thanks so much!

**Comment by brenoprata10** [comment]
You rock @mehalter!
