### ISSUE TITLE
Smarter handling of quoted colors

### ISSUE THREAD

**Issue by MikeOlsen** [brenoprata10/nvim-highlight-colors#115]
Would prefer to have the virtual text come before quotes, but still keep it inside for larger texts containing multiple color codes

Current behavior:
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/8173625/21238d67-4bfa-4178-b04a-579e3e69b328)

Edited image with desired behavior:
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/8173625/866cfd83-7a9a-47e2-9ea2-99243e19c32b)

**Comment by brenoprata10** [comment]
Hey o/
Sorry, but I do not plan to add this config. I would like to keep the plugin as easy to maintain as possible :)
