### ISSUE TITLE
How to disable 0x hex highlight

### ISSUE THREAD

**Issue by heliosgo** [brenoprata10/nvim-highlight-colors#117]
Thanks your nice work. Is there any way to distinguish color and address? Or other ordinary hex? I thought about it and it was difficult. Is it possible to add an option `enable_0x_hex`?https://github.com/brenoprata10/nvim-highlight-colors/blob/a8f6952cb1ff7bde864a34c502f1a42c360a6662/lua/nvim-highlight-colors/color/utils.lua#L56-L60
![image](https://github.com/user-attachments/assets/188d4b35-9b9e-4240-87a5-1dd77d6f89fa)

**Comment by brenoprata10** [comment]
It's best if you use 
```
-- Exclude filetypes or buftypes from highlighting e.g. 'exclude_buftypes = {'text'}'
    	exclude_filetypes = {},
    	exclude_buftypes = {}
```

**Comment by heliosgo** [comment]
> It's best if you use
> 
> ```
> -- Exclude filetypes or buftypes from highlighting e.g. 'exclude_buftypes = {'text'}'
>     	exclude_filetypes = {},
>     	exclude_buftypes = {}
> ```

Thanks. Maybe it's not the best for me.
