### ISSUE TITLE
it's not working in "realtime"

### ISSUE THREAD

**Issue by osamaaj03** [brenoprata10/nvim-highlight-colors#119]
Hi, thanks a lot for the plugin it's really awesome. but recently I started to have a problem where the colors don't update till I quite insert mode otherwise it stays stuck on the same color if any, I don't know if this is the intended behavior but it used to work just fine, I haven't changed anything in the default config. thought at first that flutter colors might have not been supported properly yet but I tried hex colors too and they also had the same issue

**Comment by brenoprata10** [comment]
Hey o/
This change was applied to improve performance and to fix some issues I had with the LSP integration, the colors will now only appear/update once you quit insert mode :)

**Comment by osamaaj03** [comment]
Oh OK, glad to hear that wasn't an issue. But can we have the old less efficient realtime color update way as a option or would be hard to implement, hope I'm not asking for much "•-•

**Comment by brenoprata10** [comment]
Unfortunately, it would break in some cases, you probably have not seen the bugs yourself, but they were there hahahaha
I also don't really want to maintain two separate rendering logic, that would be a pain to deal with :(

**Comment by osamaaj03** [comment]
Very Understandable, I'm gonna keep using it anyway it's still better and more consistent than the alternatives I tried. Thanks again for your hard work <3
