### ISSUE TITLE
Support for `hsl(a)`and color names (e.g. `blue` or `Blue`)

### ISSUE THREAD

**Issue by jasper-schnabel** [brenoprata10/nvim-highlight-colors#13]
Hi,

Thanks for the really cool plugin, I'm loving it so far, I really like it's simplicity and easy usage.

I would like to see support being added for the `hsl()` and `hsla()` function, just like the `rgb()` and `rgba()`.
It would also be great to see support for the name codes like `blue` or `Blue`.

Thanks

**Comment by brenoprata10** [comment]
Hey o/
I'm glad you're enjoying it. I'll take a look on it this weekend :smiley:

**Comment by brenoprata10** [comment]
@jasper-schnabel HSL support has just been added, could you give it a try and report any bugs you may find? :confetti_ball:

**Comment by brenoprata10** [comment]
The plugin should also detect CSS colors now, let me know if you find any bugs

**Comment by jasper-schnabel** [comment]
Thanks for the extremely fast implementation, everything works exactly as I imagined it. Thank you very much!
One last question, would it be possible that `hsla()` functions are also being highlighted, that would be great.
![screenshot_2022-08-12_19:21:35](https://user-images.githubusercontent.com/67754783/184411116-0f3a56aa-f486-49cd-a766-d3113a12ba04.png)

**Comment by brenoprata10** [comment]
I just added it, should be working fine now

**Comment by jasper-schnabel** [comment]
Thank you very much!
It works wonderfully. I really appreciate the quick responds :+1:
