### ISSUE TITLE
Highlight colours in nvim-cmp documentation window?

### ISSUE THREAD

**Issue by megalithic** [brenoprata10/nvim-highlight-colors#15]
Bravo! Great plugin; is there a way to highlight the matched colour patterns in the `nvim-cmp` documentation popup window?

**Comment by brenoprata10** [comment]
Good to see you're enjoying it!
I'll take a look when i am available, there are few enhancements that need to be finished before i can check this one :smiley:

**Comment by brenoprata10** [comment]
In the meanwhile, Could you specify what you have in mind? Maybe a screenshot would make it easier to understand o/

**Comment by megalithic** [comment]
Fantastic, and absolutely!

Here's the main use case I'm after (with tailwindcss lsp):

<img width="1564" alt="image" src="https://user-images.githubusercontent.com/3678/183708262-5b4ad176-be9a-4e56-a4de-51ec85430665.png">

**Comment by brenoprata10** [comment]
I see, it would look pretty cool, i'll see what i can do when i have some free time 😄

**Comment by brenoprata10** [comment]
I don't think we can change highlight of nvim-cmp, but i added tailwind highlight support, simply pass:
```
require('nvim-highlight-colors').setup {
   enable_tailwind = true
}
```
and you will get highlight support for all tailwind colors:
![image](https://user-images.githubusercontent.com/26099427/184542407-7367eb17-0ca0-4970-825b-b43a7da9d8e8.png)

**Comment by siduck** [comment]
@brenoprata10 how does the highlighting work in cmp when there's no lsp attached to its buffer + so we wont get colors from lsp :thinking: 

![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/59060246/9fcd2a74-d666-4dc5-96a9-16dfeb24b1fc)

**Comment by brenoprata10** [comment]
The plugin has tailwind colors built in, the LSP was recently added a few weeks ago. The tailwind LSP is a great addition because now your  "tailwind.config" file will be scanned and highlighted as well :)

As for nvim-cmp highlighting. I've already tried adding proper support to it and it worked nicely, but it damaged performance by a lot. I will create an issue to hide the plugin for nvim-cmp completition

**Comment by brenoprata10** [comment]
I still have not given up on the nvim-cmp highlighting, because I also want to use it hahahahah
We will see what happens

**Comment by siduck** [comment]
> I still have not given up on the nvim-cmp highlighting, because I also want to use it hahahahah We will see what happens

at this point its better performance wise to just highlight via the cmp's format option :smile:

**Comment by siduck** [comment]
> As for nvim-cmp highlighting. I've already tried adding proper support to it and it worked nicely, but it damaged performance by a lot. I will create an issue to hide the plugin for nvim-cmp completition

the tailwind colors come purely from the lsp's colorprovider right? how would it work  on  cmp then, cuz its  buf doesnt have lsp attached!

**Comment by brenoprata10** [comment]
It does not, tailwind is built into this plugin too. It will work even without a supported LSP. You can disable it with `enable_tailwind = false`
