### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by nagy135** [brenoprata10/nvim-highlight-colors#2]
Hello, loving plugin so far. Just asking for this little feature, there should be internal state holding if its open and command to Toggle it. This is very easy to script ourselves (outside of plugin), but there is no reason to not have it inside plugin, dont you think?

Also sidenote, you should mention these two in README, as long as we just gonna bind it, there is no reason to use "User Command"
```
lua require("nvim-highlight-colors").turnOff()
lua require("nvim-highlight-colors").turnOn()
```

**Comment by brenoprata10** [comment]
Hello o/
I am quite new to lua and neovim plugin development, what do you mean by `internal state holding if it's opened`? I use windows to display the colors and they are toggled on and off based on the user scroll. So i don't really know what you are asking for :p

PS: Thanks for the kind words =)

**Comment by nagy135** [comment]
what it means is ... you have 2 separate binds, open and close. What plugins usually do is have also third option "toggle" that does always the opposite. So you as a developer would simply have boolean variable with scope of your module and simply flip it back and forth. I might create PR when i get time, this is just a suggestion and its very simple :)

**Comment by brenoprata10** [comment]
Ah now i get it, i'll add it to my TODO list, it should not take long to implement :)
