### ISSUE TITLE
[Feature Request] Support colour names without `:` or `=` prefix.

### ISSUE THREAD

**Issue by Akianonymus** [brenoprata10/nvim-highlight-colors#23]
```
black
: black
```

Basically both should get highlighted.

Like this, 

![image](https://user-images.githubusercontent.com/32216346/185439169-97d2d1b4-89c0-4583-9054-a716fd4cdb47.png)

Maybe a config option and disabled by default, so existing don't get disrupted.

**Comment by brenoprata10** [comment]
This behavior will not be supported. It could cause a lot of issues for other cases
