### ISSUE TITLE
WinScrolled autocmd should run only if `is_loaded` 

### ISSUE THREAD

**Issue by fitrh** [brenoprata10/nvim-highlight-colors#27]
[20220910_191350_wf.webm](https://user-images.githubusercontent.com/55179750/189480919-fd4fa3b0-b2e3-429a-99ce-953b3e5eacf3.webm)

The above video shows the color returns when we scroll even though we turn it off, this is because of this autocmd

https://github.com/brenoprata10/nvim-highlight-colors/blob/e2ebd0ce72a77f2f44a8cf980c1bc1226f2e8395/lua/nvim-highlight-colors/init.lua#L150-L152

`update_windows_visibility` should only be called (or protected) if `is_loaded`

This patch solves the issue

```diff
diff --git a/lua/nvim-highlight-colors/init.lua b/lua/nvim-highlight-colors/init.lua
index 26168c2..e177d2d 100644
--- a/lua/nvim-highlight-colors/init.lua
+++ b/lua/nvim-highlight-colors/init.lua
@@ -148,7 +148,12 @@ vim.api.nvim_create_autocmd({"TextChanged", "TextChangedI", "TextChangedP", "Vim
 })
 
 vim.api.nvim_create_autocmd({"WinScrolled"}, {
-	callback = update_windows_visibility,
+	callback = function()
+                if not is_loaded then
+                        return false
+                end
+                update_windows_visibility()
+        end,
 })
 
 vim.api.nvim_create_autocmd({"BufEnter"}, {
```

Sorry for not making a PR, the patch was made by skimming the `init.lua` file, I haven't even finished reading the file, so I doubt I understand this plugin as a whole

Also, it is always a best practice to keep autocmds under an augroup

**Comment by brenoprata10** [comment]
Thank you for reporting and taking your time with it :)
I'll have time to fix it tomorrow o/
