### ISSUE TITLE
would you consider alternate swatch positions?

### ISSUE THREAD

**Issue by benfrain** [brenoprata10/nvim-highlight-colors#3]
Firstly, thanks for making this. The fact it evaluates `var(--custom)` is great – don't know of another neovim plugin doing that 👍

I've come from using colorizer and find it very odd to look to the left column to see a color defined further along the line. Do you have any other layout options in mind in future? Or perhaps implementing the 'colorizer' style with bg highlighted in the color?

**Comment by brenoprata10** [comment]
My plan is to offer the option to color the background as well as colorizer, there are some code already done that can make that kind of behavior, but it's not yet ready =)

**Comment by brenoprata10** [comment]
Render options has just been added with commit: https://github.com/brenoprata10/nvim-highlight-colors/commit/7ac416cd4b8637324f1b71f62092a3e5f47c108c

**Comment by brenoprata10** [comment]
I still need to figure a way around contrast colors(white background will hide the characters), i'll check it once i have another 30 minutes worth of free time :)

**Comment by brenoprata10** [comment]
Ping @benfrain  :rocket:

**Comment by benfrain** [comment]
Fantastic! Look forward to trying it out.
