### ISSUE TITLE
Can I make it on by default?

### ISSUE THREAD

**Issue by c02y** [brenoprata10/nvim-highlight-colors#33]
It seems I have to turn it on manually to display the colors.

**Comment by brenoprata10** [comment]
Hello, yes it is possible, follow the docs here:
Call setup function to initialize plugin by default:

require('nvim-highlight-colors').setup {}

**Comment by c02y** [comment]
Sorry about that, I have to (sometimes unnecessary) run `:PackerCompile` to make the config work after I edit the config file.

Stupid Packer.
