### ISSUE TITLE
[Feature Request] Add 0xrrggbb pattern

### ISSUE THREAD

**Issue by ReKreker** [brenoprata10/nvim-highlight-colors#34]
Is it possible to add hex pattern to view color?
![image](https://user-images.githubusercontent.com/106391109/227599360-97be6e8f-0705-4dde-a6a8-8f3945831c59.png)

**Comment by brenoprata10** [comment]
Done 😄 
Could you please do some testing in your env?
![image](https://user-images.githubusercontent.com/26099427/227625346-e7a10c76-3704-47a4-9d8b-a09b0f104afa.png)
