### ISSUE TITLE
Wrong highlighting in Ruby RSpec file

### ISSUE THREAD

**Issue by arutinn** [brenoprata10/nvim-highlight-colors#45]
The plugin detects the beginning of the method names as a hex color value and highlights it which is incorrect behavior.
<img width="237" alt="Screenshot 2023-08-16 at 11 29 39" src="https://github.com/brenoprata10/nvim-highlight-colors/assets/23014457/67459924-19a9-4d30-a98b-e115a3a02fd1">

**Comment by brenoprata10** [comment]
already reported here: https://github.com/brenoprata10/nvim-highlight-colors/issues/43
I will take a look once I have some free time :)
