### ISSUE TITLE
Add tailwind extended color support

### ISSUE THREAD

**Issue by a-priestley** [brenoprata10/nvim-highlight-colors#48]
[For reference...](https://tailwindcss.com/docs/adding-custom-styles)

Custom colors defined as per above, do not show up with this plugin, as they would not be added to [tailwind.lua](https://github.com/brenoprata10/nvim-highlight-colors/blob/main/lua/nvim-highlight-colors/named-colors/tailwind.lua).

A good way of accomplishing this might be to traverse for the configuration file (tailwind.config.js / tailwind.config.mjs) and get the key-value pairs from `theme.extend.colors`.

**Comment by brenoprata10** [comment]
I am planning to add support to LSP. This way we can support CSS, Tailwind and pretty much any language and config. It will take some time, but I think it's doable :)

**Comment by brenoprata10** [comment]
With LSP support that will be released in a few days, you will have this behavior once you configure `tailwindcss` LSP. I've tested on my projects and it works like a charm :)

**Comment by a-priestley** [comment]
I hadn't considered doing it through LSP! Fantastic!

**Comment by brenoprata10** [comment]
Merged, i recommend configuring https://github.com/tailwindlabs/tailwindcss-intellisense in your config for this change to take effect :)

**Comment by a-priestley** [comment]
Seems to be working beautifully -- great addition!
