### ISSUE TITLE
Text's foreground color sometimes looks hard to see on `background` render option

### ISSUE THREAD

**Issue by cpea2506** [brenoprata10/nvim-highlight-colors#5]
Hi. Thanks for your effort to create this plugin. I've waited a long time for `background` display feature and now it's available. However, the foreground color sometimes looks hard to see. 
I see `Colorizer` plugin render its text with `black or white` based on color value. Hopefully, this can be improved in the future. 😊

<img width="225" alt="Screenshot 2022-08-03 at 17 47 14" src="https://user-images.githubusercontent.com/42694704/182590342-cc1330cf-c5f1-44c9-971c-042a42eb60f4.png">

**Comment by brenoprata10** [comment]
Hey o/
I has just released the background and foreground options, i am aware of this issue and i will have time to fix it this weekend :)

**Comment by brenoprata10** [comment]
For now i recommend using the foreground option as it's slightly better to read in most cases

**Comment by brenoprata10** [comment]
Should be good for now, let me know if you have any feedback from it :)

**Comment by cpea2506** [comment]
> Should be good for now, let me know if you have any feedback from it :)

Yes. I really like it. 😄

I think we can improve more on how it display foreground color. Like this color should better have black color instead of white.

<img width="179" alt="Screenshot 2022-08-07 at 21 42 48" src="https://user-images.githubusercontent.com/42694704/183296464-e077d7e3-eabc-4801-bc81-caa0e09f3c71.png">

**Comment by cpea2506** [comment]
Follow this [SO](https://stackoverflow.com/a/3943023/16807083) answer. I found this is what i expected:

The current method:
<img width="288" alt="Simple" src="https://user-images.githubusercontent.com/42694704/183299902-87d98f82-a4b0-42fe-9714-d55abc63c8e0.png">

The SO method:

> for each c in r,g,b:
>    c = c / 255.0
>    if c <= 0.04045 then c = c/12.92 else c = ((c+0.055)/1.055) ^ 2.4
> L = 0.2126 * r + 0.7152 * g + 0.0722 * b

<img width="276" alt="Advance" src="https://user-images.githubusercontent.com/42694704/183299887-c9351b3a-6b80-40b7-8146-066a6e7215b7.png">

**Comment by brenoprata10** [comment]
I see you already started implementing it :rocket:, do you pretend to open a PR with it?

**Comment by cpea2506** [comment]
> I see you already started implementing it 🚀, do you pretend to open a PR with it?

Yes sure. I just need a time to make sure it was implemented properly. 😄
