### ISSUE TITLE
#53 breaks lua paths

### ISSUE THREAD

**Issue by BerkeleyTrue** [brenoprata10/nvim-highlight-colors#54]
I see this code added last week does not properly append to path. It should prepend a ';' before adding 

https://github.com/brenoprata10/nvim-highlight-colors/blob/main/lua/nvim-highlight-colors/init.lua#L11C1-L12C68

```
local lua_rocks_deps_loc = vim.fn.expand("<sfile>:h:r") .. "/../lua/example-plugin/deps"
package.path = package.path .. lua_rocks_deps_loc .. "/lua-?/init.lua"

```

Also, I don't see the point of this code? Is this some sort of development utility? It doesn't point to anything on my system and it is needlessly polluting user space paths.

![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/6775919/ff338311-9cd2-468b-999c-2096819c05ce)

**Comment by brenoprata10** [comment]
This was fixed on my latest commit
