### ISSUE TITLE
regex of custom_colors didn't work as I intend

### ISSUE THREAD

**Issue by Jaehaks** [brenoprata10/nvim-highlight-colors#55]
Hi brenoprata10, 
I write a regex to detect like 'r' or "r" and want to show the color ##FF0000 like this 
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/26200835/55760ecb-1d13-479c-958e-aa88fe5fafa4)

But the 'r' is not detected although the regex works when i write in search command.
what is different in the custom_colors region?

**Comment by Jaehaks** [comment]
> Please follow the example provided in the docs:
> 
> ```
> lua require("nvim-highlight-colors").setup {
> 	render = 'background', -- or 'foreground' or 'first_column'
> 	enable_named_colors = true,
> 	enable_tailwind = false,
> 	custom_colors = {
> 		-- label property will be used as a pattern initially(string.gmatch), therefore you need to escape the special characters by yourself with % 
> 		{label = '%-%-theme%-font%-color', color = '#fff'},
> 		{label = '%-%-theme%-background%-color', color = '#23222f'},
> 		{label = '%-%-theme%-primary%-color', color = '#0f1219'},
> 		{label = '%-%-theme%-secondary%-color', color = '#5a5d64'},
> 		{label = '%-%-theme%-contrast%-color', color = '#fff'},
> 		{label = '%-%-theme%-accent%-color', color = '#55678e'},
> 	}
> }
> ```

you mean that % is used instead of \ ?

**Comment by brenoprata10** [comment]
Yes, that's how lua patterns works, lua does not have regex
