### ISSUE TITLE
Support for #rrggbbaa and #rgba syntax

### ISSUE THREAD

**Issue by benfrain** [brenoprata10/nvim-highlight-colors#6]
With CSS it is common to define an alpha layer using HEX eg #0008 (or 8-digit #00000088) for a semi-transparent black. Would be very useful to have support for that.

**Comment by brenoprata10** [comment]
Just added it, let me know if you find any bugs

**Comment by benfrain** [comment]
Hey, do you have Ko-Fi or paypal setup? I’d like to buy you a coffee to say thanks for all your work on this plugin 👍

**Comment by brenoprata10** [comment]
I appreciate the gesture, I have github sponsor configured for the project, there is a single payment tier that is exactly a "Cup of coffee" XD
https://github.com/sponsors/brenoprata10

**Comment by brenoprata10** [comment]
There is a sponsor button on the top right part of the screen, right next to `Watch` button

**Comment by benfrain** [comment]
> There is a sponsor button on the top right part of the screen, right next to `Watch` button

Yes, and clicking that does nothing but take me back to the homepage.

https://user-images.githubusercontent.com/1318466/184162157-656048b0-3d92-4df7-9a76-5af72f045fb8.mov

**Comment by brenoprata10** [comment]
WTF! :smile: 
Let me check my github account

**Comment by brenoprata10** [comment]
It should work now

**Comment by benfrain** [comment]
Yep, just done it. Hope you get plenty more 👍

**Comment by brenoprata10** [comment]
Hey 👋
Thanks a lot! I just got an email confirming it 😃
