### ISSUE TITLE
"Invalid espace sequence" bug on Windows

### ISSUE THREAD

**Issue by adelarsq** [brenoprata10/nvim-highlight-colors#7]
Using on Windows on the startup shows the message "Invalid espace sequence":

![image](https://user-images.githubusercontent.com/430272/182882619-9bbcd674-c63a-473d-82db-c694e346d775.png)

Appears that is related with the paths.

**Comment by brenoprata10** [comment]
Unfortunately i do not have a windows to test this one :sweat_smile: 
I'll check how other plugins are handling this :)
