### ISSUE TITLE
Add inline virtual text option

### ISSUE THREAD

**Issue by mehalter** [brenoprata10/nvim-highlight-colors#70]
The virtual text option is great and much less intrusive than foregound/background but it can be hard to read when lines have multiple colors. Neovim v0.10 is adding support for inline virtual text (powers stuff like inlay hints) which is an amazing use case for this plugin! It would be awesome to get inline virtual color symbols

Relevant upstream: https://github.com/neovim/neovim/pull/20130

A pull request I cobbled together for another color highlighting plugin that is no longer maintained: https://github.com/NvChad/nvim-colorizer.lua/pull/63

I'm not sure if I'll have time to put together a similar PR here, but if I do get the time I definitely will!

**Comment by brenoprata10** [comment]
Hey o/
I am already aware of this config. I am just waiting for it to be released to properly add support to it :)

**Comment by mehalter** [comment]
0.10 released 🥳

**Comment by brenoprata10** [comment]
Will get to it this weekend 👍

**Comment by brenoprata10** [comment]
Done, feel free to reopen if you notice any bugs 👍
