### ISSUE TITLE
regex [set] does not work 

### ISSUE THREAD

**Issue by Jaehaks** [brenoprata10/nvim-highlight-colors#71]
If I set the pattern with [set], it does not work

1) label  = 'red'     => works for all red
2) label = '%'red%'' => works for all 'red'
3) label = '%'red%'' => works for all 'red'
3) label = "[']red[']" => not work

is it normal?

**Comment by brenoprata10** [comment]
Hello,
What do you mean by "set'?
Could you provide more information?

**Comment by brenoprata10** [comment]
BTW, as far as i can see, It's working as expected. I recommend experimenting with `string.gmatch` function in lua as this is what I use to run the lua patterns

**Comment by Jaehaks** [comment]
@brenoprata10   That may be a siliiy question, 
Could you give me some example what you tested? 
the set means that character sets in lua regex pattern as [Programming in Lua : 20.2](https://www.lua.org/pil/20.2.html)
>A char-set allows you to create your own character classes, combining different classes and single characters between square brackets. For instance, the char-set '[%w_]' matches both alphanumeric characters and underscores, the char-set '[01]' matches binary digits, and the char-set '[%[%]]' matches square brackets. To count the number of vowels in a text, you can write

I tested with `string.gmatch`, its pattern worked, but the pattern does not in only `nvim-highlight-colors`

I tested the pattern in test.lua file like this 
```lua
s = "hello world from Lua red 'red' \"red\" UredP"
for w in string.gmatch(s, "[\'\"]red[\"\']") do
	print(w)
end
```

and the result is successful what I intend to
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/26200835/3ce1daf1-40b5-4103-b2a4-0b016b317c20)

If I configure like below code
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/26200835/8aeaf527-79be-43a6-81a7-36d34dd27dd8)
the 'red' and "red" does not be highlighted 

but do you mean that these pattern works successful?

**Comment by brenoprata10** [comment]
The custom_colors property is not meant to receive a lua pattern. The mention of gsub is mostly to escape the possible characters that might create a conflict when running the pattern on the plugin side. You should stick with any of the these you already tried:
label = 'red' => works for all red
label = '%'red%'' => works for all 'red'
label = '%'red%'' => works for all 'red'

**Comment by Jaehaks** [comment]
@brenoprata10 I understand, Thank you~!
