### ISSUE TITLE
The scrolling performance downgraded a lot recently

### ISSUE THREAD

**Issue by nyngwang** [brenoprata10/nvim-highlight-colors#72]
To test it, have a buffer containing many color codes `#abcdef` and scroll it using `<C-d>`, `<C-u>`.

This is my current config:

```lua
require('nvim-highlight-colors').setup {
  render = 'virtual',
  enable_named_colors = true,
  enable_tailwind = true,
}
```

If I disable this plugin then the problem disappears.

---

I saw your usage of `WinScrolled` but that's probably not a good idea. From my experience, it slows down things a lot.

2c75876

**Comment by nyngwang** [comment]
Just confirmed: rollbacked to d711574 solves the lagging issue. The culprit is 2c75876 :(

**Comment by brenoprata10** [comment]
Hey o/
Thanks for reporting it, It's not the LSP fault, I will fix it tomorrow :)

**Comment by brenoprata10** [comment]
I have just pushed a code that fixes the performance issue. Could you give it a try and report back to me?
Thanks for taking your time with it 😃

**Comment by nyngwang** [comment]
It works great now :) Thank you!
