### ISSUE TITLE
Having the same buffer opened on multiple windows might remove highlighting

### ISSUE THREAD

**Issue by igorlfs** [brenoprata10/nvim-highlight-colors#76]
Hey!

I'm trying out the plugin, it's pretty great so far! However, I found an issue: if I open the same buffer twice, the second window's highlights "track" the first window's position. And what I mean by that is, if the second window contains a color that should be highlighted, but it isn't inside the first window's "frame", it won't be highlighted. It's easier to show with a picture:

![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/84649544/4c9b6c50-adba-42f9-947b-9830311e38c3)

Here, on the left, is the first window, where highlighting is working just fine. On the right, the colors `#f9e2af`, `#cba6f7`, `#89dceb` aren't highlighted because they aren't showing up in the first window.

EDIT: by the way, I'm on nightly

**Comment by brenoprata10** [comment]
Hey o/
I control which buffer to be highlighted based on their id, it makes sense that if you open the same buffer, it would generate this behavior. But to be honest it's not something that i would be willing to spend time to fix. As this will only happen if you have the same buffer opened twice. Which I doubt many people would use such setup in their workflow. 
I will be closing the issue.

**Comment by rockyzhang24** [comment]
However, using a split window having the same buffer is very common when referencing a different part of code.
