### ISSUE TITLE
Feature Request: configuration options for regex patterns

### ISSUE THREAD

**Issue by igorlfs** [brenoprata10/nvim-highlight-colors#77]
Hello, there!

I've noticed a lot of false positives in some file types (as some people pointed out in #28). While the original issue suggests a filetype-based configuration, I wonder if a better approach would be to control some highlight patterns, similar to the options `enable_tailwind` and `enable_named_colors`. My goal is to disable the `#XXX` pattern altogether.

**Comment by thetic** [comment]
I would also like to be able to disable the `#XXX` pattern specifically. It is almost entirely false positives in my usage.

**Comment by brenoprata10** [comment]
Done with: https://github.com/brenoprata10/nvim-highlight-colors/pull/87
Check Readme for more info
