### ISSUE TITLE
Errors with PackerSync from packer.nvim

### ISSUE THREAD

**Issue by assistcontrol** [brenoprata10/nvim-highlight-colors#8]
I use a simple setup with `packer.nvim`:

```lua
    use {'brenoprata10/nvim-highlight-colors', config = function()
        require('nvim-highlight-colors').setup()
    end}
```

It produces this error on `:PackerSync`, dozens of times:
```
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display
.lua:289: attempt to perform arithmetic on a nil value
stack traceback:
        .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:289: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display
.lua:262: attempt to perform arithmetic on a nil value
stack traceback:
        .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:262: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

I've narrowed it down to this plugin. Issuing `:HighlightColorsOff` first does not prevent the errors. Only disabling this plugin entirely seems to fix it.

Am I the only one?

**Comment by brenoprata10** [comment]
What happens if you use this way?
```
use {'brenoprata10/nvim-highlight-colors', config = function()
        require('nvim-highlight-colors').setup {}
    end}
```

**Comment by assistcontrol** [comment]
I still get the same errors. Also, it seems to be overriding and undoing many of the colors from gruvbox-material and mini.nvim.

**Comment by brenoprata10** [comment]
Which neovim version are you using?

**Comment by assistcontrol** [comment]
I'm running nvim 0.7.2.

If it's just me, then it's interacting with some other plugin in a strange way. My config is at https://github.com/assistcontrol/vim. If you clone my repo and `git checkout 8b1534d532db495841c3e38b04d7aed0f296064f` (the commit before I disabled the repo) you'll see the errors if you run `:PackerSync`, and you'll see that colors are mangled on the `mini.starter` start screen.

**Comment by cpea2506** [comment]
I think this have been fixed with the latest commit. I'm sure the error comes from #10

**Comment by brenoprata10** [comment]
Could you give it a try? The PR was merged this afternoon 😃

**Comment by assistcontrol** [comment]
Yup, that fixed all the problems! Thanks!
