### ISSUE TITLE
Virtual text in front of the color

### ISSUE THREAD

**Issue by simonmandlik** [brenoprata10/nvim-highlight-colors#81]
Virtual text is showing in front of the color, not behind, as shown in the examples

<img width="234" alt="image" src="https://github.com/brenoprata10/nvim-highlight-colors/assets/16707112/d89cdae4-5b91-4207-bf55-f666b5b44ffc">

I'm on NVIM v0.10.0, using the latest version of the plugin with the following lazy setup:

```lua
  {
      "brenoprata10/nvim-highlight-colors",
      opts = {
          render = "virtual",
          virtual_symbol = "",
          enable_tailwind = true
      }
  }
```

**Comment by brenoprata10** [comment]
Yes, this is the new default, i will update the readme in the comming days
