### ISSUE TITLE
Trigger in terminal - probably not intentional

### ISSUE THREAD

**Issue by bluss** [brenoprata10/nvim-highlight-colors#82]
I noticed the color highlight can trigger inside the embedded terminal (:term), here a git diff view.

![bild](https://github.com/brenoprata10/nvim-highlight-colors/assets/3209739/c82eac46-5ef0-4c18-b8c0-bb67fe44ea1f)

That's kind of cool but it's not consistent (goes away if I hide/show the terminal, for example, this is a floating terminal). For this reason I think it's best to disable this. Thanks for the nice plugin.

Config (lazy.nvim)

```lua
return {
  "https://github.com/brenoprata10/nvim-highlight-colors",
  event = "VeryLazy",
  opts = {
    render = "virtual",
    virtual_symbol = ""
  },
}
```
The virtual symbol is nf-fa-square from nerd fonts I believe.

If there was a way to turn off this plugin per buffer, I'd trigger it on buftype=terminal and turn off.

**Comment by wustho** [comment]
Happens to me as well, can we have option like `exclude_filetypes`?

**Comment by bluss** [comment]
A buffer option variable (vim.b. namespace) to gate it per buffer would be the most flexible I think, then any kind of aucmd logic can be used

**Comment by brenoprata10** [comment]
@bluss  This should work with term command as well, Which command are you using to `if I hide/show the terminal,`?

**Comment by brenoprata10** [comment]
I've removed the plugin usage for the terminal buffer. Feel free to reopen this issue if you find any bugs

**Comment by bluss** [comment]
thanks for that! I didn't answer the question yet, but it's :ToggleTerm (from that toggleterm plugin), both terminals in floating windows and splits. The color inlays are flickery when applied and may not be displayed on first toggle.  The behaviour seems more stable with just regular `:term` in a lonely window, but in splits I see the same kind of thing as with toggleterm.

As seen in the screenshot, the diff coloring (that git diff outputs) is also misplaced after the inlay is there.
