### ISSUE TITLE
[Feature Request]: Add ability to set position of inline virtual symbol

### ISSUE THREAD

**Issue by adriankarlen** [brenoprata10/nvim-highlight-colors#84]
Add config option to specify if the virtual symbol should appear before or after the identified color.

**Comment by simonmandlik** [comment]
@brenoprata10 Would you be interested in adding something like `"eow"` for `virtual_symbol_position` that would add the virtual text right after the color specification (not to the very end of the line)?

**Comment by brenoprata10** [comment]
It should already work, could you give it a try and post a screenshot here?

**Comment by brenoprata10** [comment]
Oh nevermind, this is not supported. I do not plan to create this logic. I will be sticking with what is available in neovim API

**Comment by simonmandlik** [comment]
> Oh nevermind, this is not supported. I do not plan to create this logic. I will be sticking with what is available in neovim API

This should be only a matter of shifting the start for `"inline"` version by the color code length, no?

**Comment by brenoprata10** [comment]
I am refactoring a few things today, will get to it if i have time

**Comment by brenoprata10** [comment]
Feel free to reopen this issue if you find any bugs

**Comment by simonmandlik** [comment]
Amazing, thanks!
