### ISSUE TITLE
support color value conversion?

### ISSUE THREAD

**Issue by kola-web** [brenoprata10/nvim-highlight-colors#86]
hex -> hls -> rag -> rgba

**Comment by brenoprata10** [comment]
This is in my todo list for sure, but I still need to polish some other parts of the plugin to start working on it :)

**Comment by kola-web** [comment]
Thanks for the recovery

**Comment by brenoprata10** [comment]
Hey o/
Check this plugin: https://github.com/cjodo/convert.nvim
