### ISSUE TITLE
[Bug] Invalid buffer id

### ISSUE THREAD

**Issue by fm39hz** [brenoprata10/nvim-highlight-colors#90]
since update to neovim 0.10
I'm using lazyvim with barely default config
caused when i open neo-tree with a highlight is show
```
   Error  11:15:41 AM msg_show.lua_error Error detected while processing WinScrolled Autocommands for "*":
11:15:41 AM msg_show Error executing lua callback: ...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:143: Invalid buffer id: -1358491136
stack traceback:
	[C]: in function 'nvim_buf_clear_namespace'
	...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:143: in function 'clear_highlights'
	...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:113: in function 'refresh_highlights'
	...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:166: in function <...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:164>
```

**Comment by brenoprata10** [comment]
WIll get to it today :)

**Comment by brenoprata10** [comment]
Should be fixed with my latest update. Feel free to reopen if you still see this error

**Comment by fm39hz** [comment]
the error still stand there after update, i only seen it when open neo-tree when i have git change highlight
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/71458213/adb1fcfd-a085-4e09-9443-641af857a278)
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/71458213/75cfb5d9-b816-4c78-8f55-70e39d5aa9f1)

**Comment by fm39hz** [comment]
the error still stand there after update, i only seen it when open neo-tree when i have git change highlight
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/71458213/adb1fcfd-a085-4e09-9443-641af857a278)
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/71458213/75cfb5d9-b816-4c78-8f55-70e39d5aa9f1)

**Comment by brenoprata10** [comment]
@fm39hz COuld you update and try again?

**Comment by fm39hz** [comment]
> @fm39hz COuld you update and try again?

sorry for the late reply
after update every thing looks good
thx for your hard work

**Comment by brenoprata10** [comment]
Could you show me what is shown in 
`:messages`? It's tricky to read because part of the error is not shown :(

**Comment by fm39hz** [comment]
> Could you show me what is shown in `:messages`? It's tricky to read because part of the error is not shown :(
here it is
```Error detected while processing WinScrolled Autocommands for "*":
Error executing lua callback: ...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:113: Invalid buffer id: 1886781952
stack traceback:
	[C]: in function '__index'
	...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:113: in function 'refresh_highlights'
	...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:182: in function <...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:180>
```

**Comment by brenoprata10** [comment]
Try again and let me know if the error is still happening

**Comment by fm39hz** [comment]
> Try again and let me know if the error is still happening

after this update everything seem to be good, i'm not encounter it again
