### ISSUE TITLE
tailwind highlight get lower priority

### ISSUE THREAD

**Issue by BBboy01** [brenoprata10/nvim-highlight-colors#92]
![CleanShot 2024-05-24 at 14 05 48@2x](https://github.com/brenoprata10/nvim-highlight-colors/assets/59885141/733599fc-a9b7-43d9-8475-429c0359f7b2)

in tailwind configured project, colors not use presets

**Comment by BBboy01** [comment]
Thanks for your quick reactions :)!

**Comment by BBboy01** [comment]
![CleanShot 2024-05-24 at 17 31 52@2x](https://github.com/brenoprata10/nvim-highlight-colors/assets/59885141/3023acb8-060c-4f89-b412-b9b79808257a)

but keeps issue in another case :(

**Comment by brenoprata10** [comment]
At this point i recommend disabling tailwind and using only the LSP hahhah

enable_tailwind = false

**Comment by BBboy01** [comment]
> enable_tailwind = false

it did works better in my case, thanks!
