### ISSUE TITLE
'eow' adds highlights everytime the buffer is entered

### ISSUE THREAD

**Issue by bluss** [brenoprata10/nvim-highlight-colors#93]
Hi, I just ran across this bug and would rather report it than say nothing.

Plugin version: 656ce9b

With the followng `eow` configuration, a new inlay is added every time a buffer is entered, so it stacks up and there are more and more color inlays.

![bild](https://github.com/brenoprata10/nvim-highlight-colors/assets/3209739/1c4e08c7-7863-4ba0-9bf8-db69c6a144a3)

(lazy.nvim configuration below)

```lua
return {
  "https://github.com/brenoprata10/nvim-highlight-colors",
  cmd = "HighlightColors",
  opts = {
    render = "virtual",
    virtual_symbol = "",
    virtual_symbol_prefix = ' ',
    virtual_symbol_suffix = ' ',
    virtual_symbol_position = 'eow',
  },
  keys = {
    {"<leader>uL", function() require("nvim-highlight-colors").toggle() end, desc = "Highlight Colors (toggle)"},
  },
  config = function(plugin)
    require("nvim-highlight-colors").setup(plugin.opts)
    require("nvim-highlight-colors").turnOff()
  end
}
```

**Comment by brenoprata10** [comment]
Could you check again?

**Comment by brenoprata10** [comment]
Should be fixed now :)
