### ISSUE TITLE
[BUG] named color cause tree-sitter render weird

### ISSUE THREAD

**Issue by fm39hz** [brenoprata10/nvim-highlight-colors#94]
whenever i add a Named color in code, it cause tree-sitter to render everything with that color instead of a colorscheme
edit:
my current colorscheme is [everforest](https://github.com/neanias/everforest-nvim)
before:
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/71458213/70abc087-c2a7-419d-bfc6-b7144f73da0a)
after:
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/71458213/f4c537e2-53d6-4c06-ab2c-7edb3394b9e6)
with hex color everything seem normal:
![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/71458213/d0c04032-bed8-4808-9ee6-803eb873e725)

**Comment by brenoprata10** [comment]
Hey o/
I have a good idea of what might be causing this. Thanks for reporting the issue :)

**Comment by brenoprata10** [comment]
SHould be fixed now, feel free to reopen if you find any bugs :)
