### ISSUE TITLE
Error init.lua line 222 (`then` missing)

### ISSUE THREAD

**Issue by rachartier** [brenoprata10/nvim-highlight-colors#98]
Hello,
Since the last merge, there are an error:

`vim/loader.lua:0: ...nvim-highlight-colors/lua/nvim-highlight-colors/init.lua:122: 'then' expected near 'return'`

This makes the plugin unusable...
If you want I can do a PR.

Thanks.

**Comment by blumaa** [comment]
I am also experiencing this error.

**Comment by kohane27** [comment]
I'm also having this issue

**Comment by brenoprata10** [comment]
Note to self. Add basic automated tests 

![image](https://github.com/brenoprata10/nvim-highlight-colors/assets/26099427/25211263-3fdd-47f8-93e6-49b9e3583e7b)
